# Generated by Django 4.0.6 on 2023-05-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0003_alter_door_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='is_open',
        ),
        migrations.AddField(
            model_name='action',
            name='is_thief',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
