# Generated by Django 4.0.6 on 2023-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0004_rename_type_action_is_open_action_is_thief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='is_thief',
            field=models.BooleanField(default=False),
        ),
    ]
