# Generated by Django 4.0.6 on 2023-05-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0005_alter_action_is_thief'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='door',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door.door'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='door',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='door.action'),
        ),
    ]
