# Generated by Django 4.0.6 on 2023-05-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0008_remove_action_user_action_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='door.action'),
            preserve_default=False,
        ),
    ]
