# Generated by Django 4.0.6 on 2023-05-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0009_alter_door_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='history',
        ),
        migrations.AddField(
            model_name='door',
            name='history',
            field=models.ManyToManyField(related_name='+', to='door.action'),
        ),
    ]
