# Generated by Django 4.0.6 on 2023-06-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0010_remove_door_history_door_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='is_thief',
        ),
        migrations.CreateModel(
            name='Breaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='door.door')),
            ],
        ),
    ]
