# Generated by Django 4.0.6 on 2023-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0011_remove_action_is_thief_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='breaking_history',
            field=models.ManyToManyField(related_name='+', to='door.breaking'),
        ),
    ]
